### ISSUE TITLE
crash when writing to same file

### ISSUE THREAD

**Issue by AberDerBart** [tstehr/RecipeMD#26] opened 2020-09-11 10:58 UTC
When piping the output of recipemd to the file that it reads from, it crashes with
```
Traceback (most recent call last):
  File "/home/bart/.local/bin/recipemd", line 11, in <module>
    load_entry_point('recipemd==4.0.3', 'console_scripts', 'recipemd')()
  File "/home/bart/programming/python/recipemd/.pyvenv/lib/python3.7/site-packages/recipemd/cli/main.py", line 40, in main
    r = rp.parse(src)
  File "/home/bart/programming/python/recipemd/.pyvenv/lib/python3.7/site-packages/recipemd/data.py", line 154, in parse
    self._parse_title()
  File "/home/bart/programming/python/recipemd/.pyvenv/lib/python3.7/site-packages/recipemd/data.py", line 183, in _parse_title
    raise RuntimeError(f"Invalid, title (heading with level 1) required, got "
RuntimeError: Invalid, title (heading with level 1) required, got None instead
```

steps to reproduce:

```
echo '# FOO

**4 bar**

---

- *4* baz

---

FooBarBaz
' > test.md
recipemd test.md > test.md
```

**Comment by tstehr** [comment] 2020-10-18 12:01
I belive this is not a bug in `recipemd`, but normal shell behavior. When redirecting output to a file, [your shell processes the redirection first before executing the program](https://stackoverflow.com/questions/6696842/how-can-i-use-a-file-in-a-command-and-redirect-output-to-the-same-file-without-t). By the time `recipemd` is executed, the file is already empty, which is what the error message complains about.

You can use [sponge](http://linux.die.net/man/1/sponge) to work around the problem:

```bash
echo '# FOO

**4 bar**

---

- *4* baz

---

FooBarBaz
' > test.md
recipemd test.md | sponge test.md
```

We could also provide an option to edit a file in-place like GNU sed's `-i` option. If you're interested in doing that, I'd gladly accept a pull request 😊

**Comment by tstehr** [comment] 2020-12-30 18:53
Since there has been no further activity, I'll close this for now. Please feel free to comment if you think that we need to perform further work here.

**Closed by tstehr** 2020-12-30 18:53 UTC
Labels: enhancement, implementation
